baseURL = "https://soap-wg.github.io/"
languageCode = "en-us"
title = "SOAP Project"
theme = "astatine"
publishDir = "docs"

preserveTaxonomyNames = true

# Code highlighting
pygmentsCodefences = true
pygmentsStyle = "native"

# Configure main navbar links. They can have a weight to select the order.
[[menu.main]]
    name = "Sources"
    url = "/sources/"
    weight = -150

# Site wide params and SEO
[params]
    # Site description. Individual pages can have descriptions too but if
    # missing it will fallback to that one.
    description = "Website for the Social Authentication Protocol SOAP"
    # Main image for the author. This will be the default image for SEO.
    [params.imgname]
        name = "img/overview.png"
        # Add an alt description for the image
        alt = "Overview of SOAP's design idea"
